### PR TITLE
Milestone 6

### PR DESCRIPTION
**Pull request by keshav-c**
In this, I have changed the friendship model, _from_ 
- single row bidrectional (creator <-> friend) 
_to_
- two row, unidirectional (creator -> friend; friend -> creator)
**for each friendship**. For efficiency, as per requirements.

I have written the code, and written new model specs to verify these changes

For more details:
1. In the project homepage, change the code to the current branch **m6-friendships-v2**
2. Refer to **The Lifecycle of a friendship record**, under the **Usage** section for details on implementation.

_PS_: I have worked alone on this project because I have no partner right now. I have permission from student success to do this.

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @keshav-c  , 👋 You have done a great job in this milestone 👏 

* [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created
* [ ] PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))

----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack _

**Comment by keshav-c** [comment]
- [x] _when friendship is confirmed, an additional row with reversed user-friend pair is created_
This feature is already working and [tested here](https://github.com/keshav-c/stay-in-touch/blob/d5d1eef7d6bf3fe556e6457133c873d64e3c3384/spec/models/friendship_spec.rb#L38). Details, as I said, are in the [README for the current branch](https://github.com/keshav-c/stay-in-touch/tree/m6-friendships-v2#the-lifecycle-of-a-friendship-record).

- [x] _PostsController#index displays posts in a timeline (their own posts + posts from their friends)_
Fixed in [bb58f83](https://github.com/keshav-c/stay-in-touch/pull/3/commits/bb58f83a9068aa4341733c9b9ffe2230d5c6e48d)

The failing stickler check concerns the size of the testing code in [timelines_spec.rb](https://github.com/keshav-c/stay-in-touch/blob/m6-friendships-v2/spec/features/timeline_spec.rb) which checks the posts timeline for correctness. The length of this code is because in order to do the integration test, I need to setup the test data, fill the login form, go to the correct page and then check if each post in the timeline is correct and appears in correct order.

I don't know to reduce the length here efficiently, so either I need some help to reduce the block length or please be more considerate in the review.

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

You can merge it :+1: 
Good luck with the next :handshake: 

Mael FOSSO

**Comment by keshav-c** [comment]
Thanks

**Pull request merged**
